version: '3.4'

services:
  biz.fullfodder4u.bff:
    image: ${DOCKER_REGISTRY-}bizfullfodder4ubff
    container_name: biz_fullfodder4u_bff
    build:
      context: .
      dockerfile: Biz.FullFodder4u.BFF/Biz.FullFodder4u.BFF/Dockerfile
    depends_on:
      - biz.fullfodder4u.identity.api
      - biz.fullfodder4u.orders.api
      - biz.fullfodder4u.restaurants.api

  biz.fullfodder4u.identity.api:
    image: ${DOCKER_REGISTRY-}bizfullfodder4uidentityapi
    container_name: biz_fullfodder4u_identity_api
    build:
      context: .
      dockerfile: Biz.FullFodder4u.Identity/Biz.FullFodder4u.Identity.API/Dockerfile
    depends_on:
      - postgres
      - jaeger

  biz.fullfodder4u.orders.api:
    image: ${DOCKER_REGISTRY-}bizfullfodder4uordersapi
    container_name: biz_fullfodder4u_orders_api
    build:
      context: .
      dockerfile: Biz.FullFodder4u.Orders/Biz.FullFodder4u.Orders.API/Dockerfile
    depends_on:
      - postgres
      - jaeger

  biz.fullfodder4u.restaurants.api:
    image: ${DOCKER_REGISTRY-}bizfullfodder4urestaurantsapi
    container_name: biz_fullfodder4u_restaurants_api
    build:
      context: .
      dockerfile: Biz.FullFodder4u.Restaurants/Biz.FullFodder4u.Restaurants.API/Dockerfile
    depends_on:
      - postgres
      - jaeger

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: biz_fullfodder4u_rabbitmq

  postgres:
    image: postgres:14
    container_name: biz_fullfodder4u_postgres
    restart: always

  jaeger:
    image: jaegertracing/all-in-one
    container_name: biz_fullfodder4u_jaeger
    restart: on-failure

  solr:
    image: solr:8
    container_name: biz_fullfodder4u_solr
    depends_on:
      - postgres
